name: 'code-butler for PR Review'
description: 'GitHub Action for performing code reviews using the OpenAI API.'
author: 'ouchi2501'

inputs:
  GITHUB_TOKEN:
    description: 'Derivative token for using the GitHub REST API'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true

runs:
  using: node16
  main: dist/index.js
